version: '3.7'

services:
  web:
    build: .
    command: python /pythonProject/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/pythonProject
    ports:
    - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:  # THIS HAS TO BE HERE FOR THIS SHIT TO WORK!
      POSTGRES_USER: postgres  # THIS HAS TO BE HERE FOR THIS SHIT TO WORK!
      POSTGRES_PASSWORD: postgres  # THIS HAS TO BE HERE FOR THIS SHIT TO WORK!


